name: marvel_client
description: Marvel characcters paginated display.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart:
  http:
  crypto:
  flutter_typeahead: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
