name: marvel_client
description: Marvel characters paginated display.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.3
  http: ^0.12.0+2
  crypto: ^2.1.3
  flutter_typeahead: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue/HelveticaNeue-Regular.ttf
        - asset: fonts/HelveticaNeue/HelveticaNeue-Bold.ttf
          weight: 700
