name: marvel_client
description: Marvel API Client
version: 1.0.0+55

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  crypto: ^2.1.3
  flutter_typeahead: ^1.6.1
  provider: ^3.1.0+1
  universal_html: ^1.1.6
  url_launcher: ^5.2.5
  scroll_to_index: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_test_utils: ^1.0.0
  flutter_launcher_icons: ^0.7.3
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/android-chrome-512x512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue/HelveticaNeue-Regular.ttf
        - asset: fonts/HelveticaNeue/HelveticaNeue-Bold.ttf
          weight: 700
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons/MaterialIcons-Regular.ttf
