name: Flutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:dev-web

    steps:
    - uses: actions/checkout@v2
    - name: Change source files ownership
      run: sudo chown -R cirrus:cirrus ./
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: pub run test
