name: Flutter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
    - name: Change source files ownership
      run: sudo chown -R cirrus:cirrus ./
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
    - name: Run tests
      run: sudo /home/cirrus/sdks/flutter/bin/flutter test
